"""add_present_to_eleve

Revision ID: 2c340221c725
Revises: f249a2bde8ae
Create Date: 2026-05-25 18:15:36.026727
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c340221c725'
down_revision: Union[str, None] = 'f249a2bde8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('present', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eleves', 'present')
    # ### end Alembic commands ###
