"""add_annotation_to_eleve

Revision ID: 75a28ce17015
Revises: 2c340221c725
Create Date: 2026-05-27 09:00:53.443462
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '75a28ce17015'
down_revision: str | None = '2c340221c725'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eleves', sa.Column('annotation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eleves', 'annotation')
    # ### end Alembic commands ###
