"""add_annotations_table_and_remove_annotation_from_eleve_groupe

Revision ID: bd46abdc1d2b
Revises: 75a28ce17015
Create Date: 2026-05-31 08:07:13.257736
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd46abdc1d2b'
down_revision: Union[str, None] = '75a28ce17015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eleve_id', sa.Integer(), nullable=True),
    sa.Column('groupe_id', sa.Integer(), nullable=True),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('date_saisie', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('eleves', 'annotation')
    op.drop_column('groupes', 'annotation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupes', sa.Column('annotation', sa.TEXT(), nullable=True))
    op.add_column('eleves', sa.Column('annotation', sa.TEXT(), nullable=True))
    op.drop_table('annotations')
    # ### end Alembic commands ###
