"""add_qcm_fields_to_niveau

Revision ID: e8f09c30d256
Revises: 3b34dcf81a6b
Create Date: 2026-06-23 10:18:14.475242
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8f09c30d256'
down_revision: Union[str, None] = '3b34dcf81a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Niveau', sa.Column('qcm_active', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('Niveau', sa.Column('qcm_bg', sa.Text(), nullable=True))
    op.add_column('Niveau', sa.Column('qcm_theme', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Niveau', 'qcm_theme')
    op.drop_column('Niveau', 'qcm_bg')
    op.drop_column('Niveau', 'qcm_active')
    # ### end Alembic commands ###
