"""add_annotation_to_groupe

Revision ID: f249a2bde8ae
Revises: 0002
Create Date: 2026-05-25 15:13:44.037406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f249a2bde8ae'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupes', sa.Column('annotation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupes', 'annotation')
    # ### end Alembic commands ###
